version: '3'
services:
  motting-app:
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
      args:
        - VARIANT=1.15
        - INSTALL_NODE=true
        - NODE_VERSION=lts/*
    container_name: motting-app
    ports: 
      - 3001:3001
    volumes:
      - ../:/go/src
    working_dir: /go/src
    tty: true
    stdin_open: true
    command: /bin/bash
  motting-db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --general-log=true
    container_name: motting-db
    ports:
      - '3306:3306'
    env_file:
      - ./docker/mysql/mysql.env
    volumes:
      - ./var/mysql/db/data:/var/lib/mysql
  motting-db-test:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --general-log=true
    container_name:  motting-db-test
    ports: 
      - 33333:3306
    env_file:
      - ./docker/mysql/mysql.env
    volumes:
      - ./var/mysql/db_test/data:/var/lib/mysql