@startuml add_phrase
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

browser -> api: AddPhraseRequest
api -> apidb:  AddPhrase
apidb --> api: Result
api --> browser:  AddPhraseResponse
@enduml
