@startuml allow_notify
participant Browser as browser
box "motting" #LightBlue
participant WebPushAPIServer as push
participant WebPushDataBase as pushdb
end box
participant GooglePushServer as pushserver

' ブラウザで画面表示時に公開鍵をサーバーから取得する
browser -> push: FetchPublickKeyRequest
push --> browser:  PublicKey
browser -> pushserver: RegisterPublicKey
pushserver --> browser:  RegisterPublicKeyResponse
browser -> push: AllowNotifyRequest
push -> pushdb:  AllowNotify
pushdb --> push: Result
push --> browser:  AllowNotifyResponse
@enduml
