@startuml delete_witticism
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

browser -> api: DeleteWitticismRequest
api -> apidb:  DeleteWitticism
apidb --> api: Result
api --> browser:  DeleteWitticismResponse
@enduml
