@startuml delete_phrase
participant Browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

Browser -> api: DeletePhraseRequest
api -> apidb:  DeletePhrase
apidb --> api: Result
api --> Browser:  DeletePhraseResponse
@enduml
