@startuml list_phrase
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

browser -> api: ListPhraseRequest
api -> apidb:  ListPhrase
apidb --> api: Result
api --> browser:  ListPhraseResponse
@enduml
