@startuml logout
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

/'
TODO:認証及びセッション管理は今後検討する
↓構想図
https://drive.google.com/file/d/1lyd-fZWlI13jor_3-Kw_9Nf8rg3jaW39/view?usp=sharing
'/
browser -> api: LogoutRequest
api -> apidb: Logout
apidb --> api: Result
api --> browser: LogoutResponse
@enduml