@startuml
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant WebPushAPIServer as push
participant mottingDataBase as apidb
participant WebPushDataBase as pushdb
participant WebPushBatch as batch
end box
participant GooglePushServer as google

batch -> api: fetchUsers
api -> apidb: selectUsers
apidb --> api: users
api --> batch: users
batch -> api: fetchPhrases
api -> apidb: selectPhrases
apidb --> api: phrases
api --> batch: phrases
'push server に必要な情報を取得する (Endpoint, P256dh, Auth)
batch -> pushdb: fetchSubscription
pushdb --> batch: subscription
'subscription・秘密鍵の署名・公開鍵をpush serverに送信する
batch -> google: sendNotification
google --> batch: result
google -> browser: notify
@enduml