@startuml register_user
participant Browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

Browser -> api: RegisterUserRequest
api -> apidb: RegisterUser
apidb --> api: Result
api --> Browser: RegisterUserResponse
@enduml