@startuml update_witticism
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

browser -> api: UpdateWitticismRequest
api -> apidb:  UpdateWitticism
apidb --> api: Result
api --> browser:  UpdateWitticismResponse
@enduml
