@startuml update_pushtime
participant Browser as browser
box "motting" #LightBlue
participant mottingAPIServer as api
participant mottingDataBase as apidb
end box

browser -> api: UpdatePushtimeRequest
api -> apidb:  UpdatePushtime
apidb --> api: Result
api --> browser:  UpdatePushtimeResponse
@enduml
