name: golang-ci
on: [push]
jobs:
  test:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    services:
      mysql-test:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: motting
          MYSQL_USER: motting
          MYSQL_PASSWORD: motting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go version
      - name: Get dependencies
        run: go get -v -t -d ./...
      - run: mysql -h mysql-test -u root -p root < ./.devcontainer/docker/mysql/initialize.sql
      - run: mysql -h mysql-test -u root -p root < ./.devcontainer/docker/mysql/inittable.sql
      - run: go test -v ./...
      - name: Discord notification by failure test
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Bot'
          DISCORD_AVATAR : https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          GITHUB_ACTIONS_URL : '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}?check_suite_focus=true'
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been failed test. {{ GITHUB_ACTIONS_URL }}'