name: golang-ci
on: [push]
jobs:
  build:
    defaults:
      run:
        working-directory: ./backend/motting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build
  test:
    needs: build
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    env:
      TEST_DB_HOST: 127.0.0.1
    services:
      motting-db-test:
        image: mysql:8.0.15
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: motting
          MYSQL_USER: motting
          MYSQL_PASSWORD: motting
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go version
      - name: Get dependencies
        run: go get -v -t -d ./...
      - run: mysql -h $TEST_DB_HOST --port 3306 -u root -proot < ./.devcontainer/docker/mysql/initialize.sql
      - run: mysql -h $TEST_DB_HOST --port 3306 -u root -proot < ./.devcontainer/docker/mysql/inittable.sql
      - run: go test -v ./...
  notify:
    if: ${{ always() }}
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification by failure jobs
        if: ${{ needs.build.result == 'failure' || needs.test.result == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Bot'
          DISCORD_AVATAR : https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          GITHUB_ACTIONS_URL : '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}?check_suite_focus=true'
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been failed test. {{ GITHUB_ACTIONS_URL }}'